### ISSUE TITLE
Benchmarking code

### ISSUE THREAD

**Issue by juanmed** [Santosh-Gupta/SpeedTorch#5]
Hello,

Thanks for sharing SpeedTorch. The README mentions 

> For an easy way to see if you get a speed advantage in your system, please run the benchmarking code on your system, but change the amount of data to reflect the amount that you will be working with in your application.

Where is this benchmarking code? Is it the google colab or do you have a separate `.py` script we can use? Thanks!

**Comment by Santosh-Gupta** [comment]
it's under the benchmarking section, here's a direct link 

https://colab.research.google.com/drive/1PXhbmBZqtiq_NlfgUIaNpf_MfpiQSKKs
