### ISSUE TITLE
question about speedup pytorch GPU tensor to cpu

### ISSUE THREAD

**Issue by buqing2009** [Santosh-Gupta/SpeedTorch#8]
i just want to speedup pytorch tensor from GPU to CPU, here is my original code:
`output = torch.squeeze(inference_output).data.cpu().numpy()`
the type of inference_output is tensor.cuda.
How can i use SpeedTorch to speedup this code?

**Comment by Santosh-Gupta** [comment]
I would use the data gadget, checkout the tutorial in the readme

**Comment by buqing2009** [comment]
@Santosh-Gupta, i have checked out all the tutorial in the readme, but the class DataGadget is used to transfer CPU numpy to Pytorch Cuda Variable. The input of DataGadget is only support npy file. But i want to transfer pytorch Cuda tensor to cpu numpy.

**Comment by Santosh-Gupta** [comment]
It can do both. Maybe the benchmarking notebook would be a little clearer to follow 

https://colab.research.google.com/drive/1PXhbmBZqtiq_NlfgUIaNpf_MfpiQSKKs

**Comment by buqing2009** [comment]
I transfer the original code to this:
```
        output_cudatorch = torch.squeeze(inference_output).data #pytorch cuda tensor
        h,w = output_cudatorch.shape
        sampl = np.random.uniform(low=0.0, high=192.0, size=(h, w)).astype(np.float32)
        np.save('data.npy', sampl)
        del sampl
        gadgetGPU = SpeedTorch.DataGadget('data.npy')
        gadgetGPU.gadgetInit()
        torch.cuda.synchronize()
        cupy.cuda.Device().synchronize()
        gadgetGPU.insertData(dataObject=output_cudatorch[:,:], indexes=(slice(1,h), slice(1,w)))
        output = np.frombuffer(gadgetGPU.CUPYcorpus[slice(1,h), slice(1,w)]) #numpy cpu result
        cupy.cuda.Device().synchronize()
        torch.cuda.synchronize()
```
But return following error:
```
self.CUPYcorpus[indexes] =  cupy.fromDlpack( to_dlpack( dataObject ) )
SystemError: error return without exception set
```
It seems the wrong use of indexes, i just want copy all GPU tensor data to numpy array.
Tensor shape is (400, 640).
How can i get it done?

**Comment by Santosh-Gupta** [comment]
I would check if there's a misalignment between your tensors. 

So check `gadgetGPU.CUPYcorpus[(slice(1,h), slice(1,w))]` and then check `output_cudatorch[:,:]`

**Comment by buqing2009** [comment]
I have fixed the bug, now it's working.
Here is final code:

 ```
        output_cudatorch = torch.squeeze(inference_output).data
        h,w = output_cudatorch.shape
        sampl = np.random.uniform(low=0.0, high=192.0, size=(h, w)).astype(np.float32)
        np.save('data.npy', sampl)
        del sampl
        gadgetGPU = SpeedTorch.DataGadget('data.npy')
        gadgetGPU.gadgetInit()
        torch.cuda.synchronize()
        cupy.cuda.Device().synchronize()
        with torch.no_grad():
            gadgetGPU.insertData(dataObject=output_cudatorch[:,:], indexes=(slice(0,h), slice(0,w)))
            output = cupy.asnumpy(gadgetGPU.CUPYcorpus[:, :])
        cupy.cuda.Device().synchronize()
        torch.cuda.synchronize()
```
But the **running time is the same as original code**:`output = torch.squeeze(inference_output).data.cpu().numpy()`
Is anything wrong?
the data size is about 640*400, float32 type. It took almost 430ms to copy cuda tensor data -> cpu numpy

**Comment by buqing2009** [comment]
checking tutorials in  [this](https://colab.research.google.com/drive/1PXhbmBZqtiq_NlfgUIaNpf_MfpiQSKKs#scrollTo=MCC2AXsdKi-j&line=11&uniqifier=1),
copy size is 131072, about 1/2 of mine, but the costing time is only 3ms

**Comment by buqing2009** [comment]
There was something wrong with my time-consuming method of statistics. 
I would closed it. Thanks

**Comment by wrchen530** [comment]
> I have fixed the bug, now it's working. Here is final code:
> 
> ```
>        output_cudatorch = torch.squeeze(inference_output).data
>        h,w = output_cudatorch.shape
>        sampl = np.random.uniform(low=0.0, high=192.0, size=(h, w)).astype(np.float32)
>        np.save('data.npy', sampl)
>        del sampl
>        gadgetGPU = SpeedTorch.DataGadget('data.npy')
>        gadgetGPU.gadgetInit()
>        torch.cuda.synchronize()
>        cupy.cuda.Device().synchronize()
>        with torch.no_grad():
>            gadgetGPU.insertData(dataObject=output_cudatorch[:,:], indexes=(slice(0,h), slice(0,w)))
>            output = cupy.asnumpy(gadgetGPU.CUPYcorpus[:, :])
>        cupy.cuda.Device().synchronize()
>        torch.cuda.synchronize()
> ```
> 
> But the **running time is the same as original code**:`output = torch.squeeze(inference_output).data.cpu().numpy()` Is anything wrong? the data size is about 640*400, float32 type. It took almost 430ms to copy cuda tensor data -> cpu numpy

Hi, I also found the running time with gadgetGPU is the same as the original code. May I know how you solve it in the end?
